### ISSUE TITLE
Pleqase, only one PR to add/update all compat entries

### ISSUE THREAD

**Issue by MarkNahabedian** [JuliaRegistries/CompatHelper.jl#448] opened 2023-02-06 04:21 UTC
FOR THE LOVE OF GOD why doesn't CompatHelper suggest all of its changes in a single pull request with sorted compat entries rather than opening dozens of conflicting ones?

This is infuriating.

**Comment by DilumAluthge** [comment] 2023-02-06 04:43
Duplicate of #126

**Closed by DilumAluthge** 2023-02-06 04:43 UTC
