### ISSUE TITLE
suggest adding missing compat entries in bulk

### ISSUE THREAD

**Issue by st--** [JuliaRegistries/CompatHelper.jl#403] opened 2021-11-16 18:22 UTC
If one happens to forget a [compat] section in a Project.toml altogether, then CompatHelper will create one PR per dependency. It'd be much more helpful to just add a single PR to add them in bulk - unlike compat _changes_, the new compat entries shouldn't have an effect anyways, so it should be possible to just have them in a single PR.

**Comment by devmotion** [comment] 2021-11-17 08:06
Seems to be a duplicate of https://github.com/JuliaRegistries/CompatHelper.jl/issues/126.

**Comment by DilumAluthge** [comment] 2021-11-17 14:53
Duplicate of #126

**Closed by DilumAluthge** 2021-11-17 14:53 UTC
