### ISSUE TITLE
Don't bump compat for equality specifiers

### ISSUE THREAD

**Issue by mortenpi** [JuliaRegistries/CompatHelper.jl#444] opened 2022-12-21 07:21 UTC
If you have e.g. `Foo = "=1.2.3`, CompatHelper will suggest `Foo = "=1.2.3, 1` when e.g. 1.3 comes along. I don't think it should, since if you are using an equality specifier, you probably have a good reason not to allow newer versions.

Maybe tangentially related to #266?

**Comment by Octogonapus** [comment] 2023-02-07 19:20
I think this is a duplicate of #250, which was fixed in #251, so this should be closed.

**Closed** 2023-02-07 19:33 UTC

**Comment by mortenpi** [comment] 2023-02-07 20:34
Oh, you need to set an argument to disable this. I never checked the `main()` docstring.

Then I would suggest making `bump_compat_containing_equality_specifier=false` the default, rather than `true`, although I know that would be a breaking change.
