### ISSUE TITLE
Spurious version bump PR opened when pkg server runs behind

### ISSUE THREAD

**Issue by IanButterworth** [JuliaRegistries/CompatHelper.jl#341] opened 2021-06-17 14:56 UTC
A package has
```
Foo = "0.2.3"
```
and CompatHelper just opened a PR with
```
Foo = "0.2.3, 0.2"
```

I think it's due to the pkg server running behind and not knowing about `Foo v0.2.3` that was released 2 days ago

**Comment by DilumAluthge** [comment] 2021-06-17 20:00
Probably a duplicate of #266?

I think the Pkg server is the culprit here.

If I recall correctly, for the v3 rewrite, we are going to drop Pkg server support and just always use the Git registry. @mattBrzezinski @fchorney is this correct?

If I'm recalling that correctly, then this bug will be fixed in v3.

**Comment by DilumAluthge** [comment] 2021-07-15 23:45
Closing as a duplicate of #266

**Comment by DilumAluthge** [comment] 2021-07-15 23:45
Duplicate of #266

**Closed by DilumAluthge** 2021-07-15 23:45 UTC
Labels: bug
